--
-- PostgreSQL database dump
--

\restrict pZRzAgqj0yChhB6VqxPKQDFgJ30Unriy719zd9I7N8X9LkiPBkgrbgWYhe9tded

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: letters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.letters (
    id bigint NOT NULL,
    letter_number character varying(100) NOT NULL,
    letter_date date NOT NULL,
    department_name character varying(100) NOT NULL,
    subject character varying(255) NOT NULL,
    description text NOT NULL,
    attachment character varying(255) NOT NULL,
    uploaded_by character varying(100) NOT NULL,
    remarks text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


ALTER TABLE public.letters OWNER TO postgres;

--
-- Name: letters_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.letters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.letters_id_seq OWNER TO postgres;

--
-- Name: letters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.letters_id_seq OWNED BY public.letters.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    approved_by character varying(50),
    created_at timestamp(6) without time zone,
    created_by character varying(50),
    email character varying(100) NOT NULL,
    email_verified boolean NOT NULL,
    full_name character varying(100) NOT NULL,
    mobile_number character varying(10) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    role character varying(255) DEFAULT 'IT_STAFF'::character varying NOT NULL,
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: letters id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.letters ALTER COLUMN id SET DEFAULT nextval('public.letters_id_seq'::regclass);


--
-- Data for Name: letters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.letters (id, letter_number, letter_date, department_name, subject, description, attachment, uploaded_by, remarks, created_at, updated_at) FROM stdin;
1	testletter/123	2026-07-29	IT Cell	test subject	test desc	letter from drug store_pdf.pdf	ram123	test remarks	2026-07-29 16:35:41.231092	2026-07-29 16:35:41.231092
2	test123	2026-02-09	Biochemistry	test sub	testdes	letter from drug store_pdf-1.pdf	ram123	remarkd	2026-07-29 20:43:33.283637	2026-07-29 20:43:33.283637
3	testjpeg	2026-07-13	Pathology	jpegtsest sub	jpeg desc	drug store letter_jpeg_file.jpeg	ram123	remarks	2026-07-29 20:45:44.447573	2026-07-29 20:45:44.447573
4	testletter222	2026-07-17	Radiology	radiology letter	desc radio	letter from drug store_pdf-4.pdf	ram123	remarks	2026-07-29 22:38:08.667276	2026-07-29 22:38:08.667276
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, approved_at, approved_by, created_at, created_by, email, email_verified, full_name, mobile_number, password, status, updated_at, username, role) FROM stdin;
2	\N	\N	2026-07-27 22:53:21.928418	\N	test@gmail.com	f	Test User	9876543211	password123	PENDING	2026-07-27 22:53:21.928418	test001	IT_STAFF
1	2026-07-27 21:43:48.42799	SYSTEM	2026-07-27 21:42:58.541332	\N	abhishek@gmail.com	f	Abhishek Kumar	9876543210	newpassword123	ACTIVE	2026-07-27 23:59:34.518063	abhishek	IT_STAFF
3	\N	\N	2026-07-29 02:20:48.885548	\N	raju@test.com	f	raju sharma	9276543210	Password@123	PENDING	2026-07-29 02:20:48.885548	raju	IT_STAFF
5	\N	\N	2026-07-29 07:58:34.184504	om	om@gmail.com	f	om	9098798798	om@123	PENDING	2026-07-29 07:58:34.184504	om	IT_STAFF
4	2026-07-29 09:55:07.363938	SYSTEM	2026-07-29 07:01:07.434936	ram123	ram@gmail.com	f	ram	9879879888	ram@123	ACTIVE	2026-07-31 13:35:30.340517	ram123	IT_STAFF
\.


--
-- Name: letters_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.letters_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: letters letters_letter_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.letters
    ADD CONSTRAINT letters_letter_number_key UNIQUE (letter_number);


--
-- Name: letters letters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.letters
    ADD CONSTRAINT letters_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users ukr7c96a004bv8w16jgdm8imich; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr7c96a004bv8w16jgdm8imich UNIQUE (mobile_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict pZRzAgqj0yChhB6VqxPKQDFgJ30Unriy719zd9I7N8X9LkiPBkgrbgWYhe9tded

